errors = [
    "Out of memory  - Нет памяти",
    "Identifier expected -  Идентификатор пропущен",
    "Unknown identifier -  Неизвестный идентификатор",
    "Duplicate identifier -  Двойной идентификатор",
    "Syntax error  -  Синтаксическая ошибка",
    "Error in real constant  -  Ошибка в вещественной константе",
    "Error in integer constant  -  Ошибка в целочисленной константе",
    "String constant exceeds line  -  Строковая константа превышает строку",
    "Unexpected end of file  -  Непредвиденный конец файла",
    "Line too long  -  Строка слишком длинная",
    "Type identifier expected  -  Ожидается идентификатор типа",
    "Too many open files  -  Слишком много открытых файлов",
    "Invalid file name  -  Недопустимое имя файла",
    "File not found  -  Файл не найден",
    "Disk full  -  Диск заполнен",
    "Undefined type in pointer def  -  Неопределенный тип в описании указателя",
    "Too many files -  Слишком много файлов",
    "Invalid compiler directive -  Недопустимая директива компилятора",
    "Error in type  -  Ошибка в типе",
    "BEGIN expected  -  Ожидается BEGIN",
    "END expected  -  Ожидается END",
    "Division by zero  -  Деление на нуль",
    '";" expected  -  Пропущен ";"',
    '":" expected  -  Пропущен ":"',
    '"," expected  -  Пропущен ","',
    '"(" expected  -  Пропущен "("',
    '")" expected  -  Пропущен ")"',
    '"=" expected  -  Пропущен "="',
    '":=" expected  -  Пропущен ":="',
    '"[" or "(." expected  -  Пропущен "[" или "(."',
    '"]" or ".)" expected  -  Пропущен "]" или ".)"',
    '"." expected  -  Пропущен "."',
    '".." expected  -  Пропущен ".."',
    "No enclosing For, While or Repeat statement  -  Нет закрывающих FOR, WHILE или REPEAT операторов"
]
#Список ошибок, используется в run_bot.

